### ISSUE TITLE
NMPC solving fail

### ISSUE THREAD

**Issue by samjupo** [robomechanics/quad-sdk#315] opened 2022-08-28 10:25 UTC
I follow the guidence [https://github.com/robomechanics/quad-sdk/wiki/1.-Getting-Started-with-Quad-SDK](url) and the code was compiled without errors. 
But I meet the warning **NMPC solving fail** as the images show when I use the following the commands:

- catkin_make run_tests
-  roslaunch quad_utils quad_plan.launch reference:=twist logging:=true

image-1: quadruped stands
![Screenshot from 2022-08-28 18-20-17](https://user-images.githubusercontent.com/89578017/187069144-0dc378ac-ef51-4ac5-aed0-46abe520d70b.png)

image-2: output: **NMPC solving fail** with roslaunch quad_utils quad_plan.launch reference:=twist logging:=true
![Screenshot from 2022-08-28 18-22-45](https://user-images.githubusercontent.com/89578017/187069193-943cd51f-57d8-4c37-ae72-070c21faf028.png)

image-3: output: catkin_make run_tests
![Screenshot from 2022-08-28 18-24-18](https://user-images.githubusercontent.com/89578017/187069237-9d8908ce-3100-4515-a047-ca7b7f856b25.png)

**Comment by jcnorby** [comment] 2022-08-28 19:33
Looks like this is likely a duplicate of #288, can you try that solution and see if it solves your problem?

**Comment by ardalantj** [comment] 2022-09-23 15:35
@samjupo Any updates on this?

**Comment by ardalantj** [comment] 2022-10-10 17:52
closing due to inactivity

**Closed by ardalantj** 2022-10-10 17:52 UTC
